# Generated by Django 5.0 on 2023-12-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='lugar',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
